### ISSUE TITLE
日志出现OSError: cannot identify image file错误

### ISSUE THREAD

**Issue by jp0id** [zhangyile/telegram-wechat#6]
服务正常使用，不过对方如果发表情过来，会出现
```
10-02-2023:03:06:06,521 CRITICAL [main.py:92]
      All channels initialized. 
10-02-2023:04:11:00,639 ERROR    [dispatcher.py:301]
     An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/lib/python3.6/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/opt/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 1128, in msg
    return self.process_telegram_message(bot, update)
  File "/opt/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 1340, in process_telegram_message
    slave_msg = self.slaves[channel].send_message(m)
  File "/opt/ehForwarderBot/plugins/eh_wechat_slave.py", line 676, in send_message
    img = Image.open(msg.path)
  File "/usr/lib/python3.6/site-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'storage/eh_telegram_master/Sticker_-749614495_74_1676002260.unknown'
```

![截屏2023-02-10 13 32 46](https://user-images.githubusercontent.com/35218851/218009173-d73d0f28-8cde-41a6-a5af-a8a68a5872d5.png)

**Comment by zhangyile** [comment]
不支持转发动图  0.0
